In [1]:
import pandas as pd

In [2]:
matches = pd.read_excel(r"C:\Users\George\Documents\University\Masters\DISS\Datasets\Match Dataset with Home and Away Form (4).xlsx", index_col=0)

In [3]:
matches.columns

Index(['date', 'comp_x', 'season_x', 'round_x', 'home_team', 'away_team',
       'home points', 'away points', 'home constant points',
       'away constant points', 'home GF', 'away GF', 'home adjusted GS',
       'away adjusted GS', 'home GA', 'away GA', 'home adjusted GC',
       'away adjusted GC', 'home xG', 'away xG', 'home xGA', 'away xGA',
       'home GD', 'away GD', 'home adjusted GD', 'away adjusted GD',
       'home constant GD', 'away constant GD', 'home form last 5',
       'away form last 5', 'home GD form last 5', 'away GD form last 5',
       'home constant GD form last 5', 'away constant GD form last 5',
       'home xGD', 'away xGD', 'home constant xGD', 'away constant xGD',
       'home xGD form last 5', 'away xGD form last 5',
       'home constant xGD form last 5', 'away constant xGD form last 5',
       'home points form last 5', 'away points form last 5',
       'home constant points form last 5', 'away constant points form last 5',
       'home avg pos', 'away avg pos', 'home previous position',
       'away previous position', 'home previous expected position',
       'away previous expected position', 'home previous points',
       'away previous points', 'home previous GD', 'away previous GD',
       'home previous xGD', 'away previous xGD',
       'away_team_away points_rolling_10',
       'away_team_away constant points_rolling_10',
       'away_team_away GF_rolling_10', 'away_team_away GA_rolling_10',
       'away_team_away xG_rolling_10', 'away_team_away xGA_rolling_10',
       'away_team_away adjusted GS_rolling_10',
       'away_team_away adjusted GC_rolling_10',
       'home_team_home points_rolling_10',
       'home_team_home constant points_rolling_10',
       'home_team_home GF_rolling_10', 'home_team_home GA_rolling_10',
       'home_team_home xG_rolling_10', 'home_team_home xGA_rolling_10',
       'home_team_home adjusted GS_rolling_10',
       'home_team_home adjusted GC_rolling_10'],
      dtype='object')

In [4]:
market_value_df = pd.read_excel(r"C:\Users\George\Documents\University\Masters\DISS\Datasets\MARKET VALUE DATA.xlsx", index_col=0)

In [5]:
#prem = matches[matches['comp_x'] == 'Premier League']
#prem = prem[prem['season_x'] != 2017]
matches = matches[matches['season_x'] != 2017]

In [6]:
#prem.reset_index(drop=True, inplace=True)
#prem
matches.reset_index(drop=True, inplace=True)
matches

,date,comp_x,season_x,round_x,home_team,away_team,home points,away points,home constant points,away constant points,...,away_team_away adjusted GS_rolling_10,away_team_away adjusted GC_rolling_10,home_team_home points_rolling_10,home_team_home constant points_rolling_10,home_team_home GF_rolling_10,home_team_home GA_rolling_10,home_team_home xG_rolling_10,home_team_home xGA_rolling_10,home_team_home adjusted GS_rolling_10,home_team_home adjusted GC_rolling_10
0,2018-08-03,Championship,2018,Matchweek 1,Reading,Derby County,0.0,0.9,1.0,1.0,...,NaN,NaN,0.30,1.0,0.34,2.82,NaN,NaN,NaN,NaN
1,2018-08-04,Championship,2018,Matchweek 1,Birmingham City,Norwich City,0.3,0.3,1.0,1.0,...,NaN,NaN,0.48,1.0,0.54,2.12,NaN,NaN,NaN,NaN
2,2018-08-04,Championship,2018,Matchweek 1,Brentford,Rotherham Utd,0.9,0.0,1.0,1.0,...,NaN,NaN,0.48,1.0,0.74,1.92,NaN,NaN,NaN,NaN
3,2018-08-04,Championship,2018,Matchweek 1,Bristol City,Nott'ham Forest,0.3,0.3,1.0,1.0,...,NaN,NaN,0.45,1.0,1.34,2.52,NaN,NaN,NaN,NaN
4,2018-08-04,Championship,2018,Matchweek 1,Ipswich Town,Blackburn,0.3,0.3,1.0,1.0,...,NaN,NaN,0.30,1.0,-0.16,2.32,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5967,2025-05-06,Premier League,2024,Matchweek 38,Newcastle Utd,Everton,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5968,2025-05-06,Premier League,2024,Matchweek 38,Nott'ham Forest,Chelsea,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5969,2025-05-06,Premier League,2024,Matchweek 38,Southampton,Arsenal,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5970,2025-05-06,Premier League,2024,Matchweek 38,Tottenham,Brighton,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5971,2025-05-06,Premier League,2024,Matchweek 38,Wolves,Brentford,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#new_row = pd.DataFrame({'Team': market_value_df['Team'].unique(), 'Season': 2024, 'Market Value': float('NaN')})
#market_value_df = pd.concat([market_value_df, new_row], ignore_index=True)
#market_value_df.sort_values(by=['Team', 'Season'], inplace=True)
#market_value_df.reset_index(drop=True, inplace=True)
#market_value_df.fillna(method='ffill', inplace=True)

In [8]:
def add_market_value(df, market_value_df):
    for team, season, mvalue in market_value_df.values:
        #df = df.loc[df['season_x'] == season]
        df.loc[(df['home_team'] == team) & (df['season_x'] == season), 'home_team_market_value'] = mvalue
        df.loc[(df['away_team'] == team) & (df['season_x'] == season), 'away_team_market_value'] = mvalue
    return df

In [9]:
df = add_market_value(matches, market_value_df)

In [10]:
df

,date,comp_x,season_x,round_x,home_team,away_team,home points,away points,home constant points,away constant points,...,home_team_home points_rolling_10,home_team_home constant points_rolling_10,home_team_home GF_rolling_10,home_team_home GA_rolling_10,home_team_home xG_rolling_10,home_team_home xGA_rolling_10,home_team_home adjusted GS_rolling_10,home_team_home adjusted GC_rolling_10,home_team_market_value,away_team_market_value
0,2018-08-03,Championship,2018,Matchweek 1,Reading,Derby County,0.0,0.9,1.0,1.0,...,0.30,1.0,0.34,2.82,NaN,NaN,NaN,NaN,66250000.0,9.430000e+07
1,2018-08-04,Championship,2018,Matchweek 1,Birmingham City,Norwich City,0.3,0.3,1.0,1.0,...,0.48,1.0,0.54,2.12,NaN,NaN,NaN,NaN,42500000.0,8.630000e+07
2,2018-08-04,Championship,2018,Matchweek 1,Brentford,Rotherham Utd,0.9,0.0,1.0,1.0,...,0.48,1.0,0.74,1.92,NaN,NaN,NaN,NaN,76350000.0,1.158000e+07
3,2018-08-04,Championship,2018,Matchweek 1,Bristol City,Nott'ham Forest,0.3,0.3,1.0,1.0,...,0.45,1.0,1.34,2.52,NaN,NaN,NaN,NaN,72550000.0,8.310000e+07
4,2018-08-04,Championship,2018,Matchweek 1,Ipswich Town,Blackburn,0.3,0.3,1.0,1.0,...,0.30,1.0,-0.16,2.32,NaN,NaN,NaN,NaN,26850000.0,3.475000e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5967,2025-05-06,Premier League,2024,Matchweek 38,Newcastle Utd,Everton,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,659650000.0,3.238000e+08
5968,2025-05-06,Premier League,2024,Matchweek 38,Nott'ham Forest,Chelsea,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,376900000.0,1.110000e+09
5969,2025-05-06,Premier League,2024,Matchweek 38,Southampton,Arsenal,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,268800000.0,1.170000e+09
5970,2025-05-06,Premier League,2024,Matchweek 38,Tottenham,Brighton,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,801700000.0,5.581000e+08
5971,2025-05-06,Premier League,2024,Matchweek 38,Wolves,Brentford,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,361100000.0,4.327300e+08

In [11]:
df.to_excel(r"C:\Users\George\Documents\University\Masters\DISS\Datasets\Match Dataset with Market Values (5).xlsx")