In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\George\Documents\University\Masters\DISS\Datasets\Match Dataset with Average Position and General Form (2).xlsx", index_col=0)

In [3]:
df.columns

Index(['date', 'comp', 'round', 'venue', 'result', 'gf', 'ga', 'opponent',
       'xg', 'xga', 'season', 'team', 'new_team', 'xGD', 'GD', 'points',
       'league_diff', 'xGD_league_diff', 'GD_league_diff', 'GF_league_diff',
       'GA_league_diff', 'xG_league_diff', 'xGA_league_diff',
       'league_weighted_points', 'league_weighted_xGD', 'league_weighted_GD',
       'league_weighted_GF', 'league_weighted_GA', 'league_weighted_xG',
       'league_weighted_xGA', 'new_team_previous_points',
       'new_team_previous_xGD', 'new_team_previous_GD',
       'new_team_previous_position', 'new_team_previous_expected_position',
       'Adjusted GS', 'Adjusted GC', 'Adjusted GD', 'new_team_avg_pos',
       'constant_points', 'constant_xGD', 'constant_GD',
       'league_weighted_points form last 5', 'league_weighted_xGD form last 5',
       'league_weighted_GD form last 5', 'constant_points form last 5',
       'constant_xGD form last 5', 'constant_GD form last 5',
       'Adjusted GD form last 5'],
      dtype='object')

In [4]:
df.drop(columns=['team','league_diff',
       'xGD_league_diff','GD_league_diff', 'GF_league_diff',
       'GA_league_diff', 'xG_league_diff', 'xGA_league_diff', 'gf', 'ga','xGD','GD','xg', 'xga', 'points'], inplace=True)

In [5]:
merged = df.merge(df, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [6]:
merged

,date,comp_x,round_x,venue_x,result_x,opponent_x,season_x,new_team_x,league_weighted_points_x,league_weighted_xGD_x,...,constant_points_y,constant_xGD_y,constant_GD_y,league_weighted_points form last 5_y,league_weighted_xGD form last 5_y,league_weighted_GD form last 5_y,constant_points form last 5_y,constant_xGD form last 5_y,constant_GD form last 5_y,Adjusted GD form last 5_y
0,2017-08-11,Premier League,Matchweek 1,Home,W,Leicester City,2017,Arsenal,3.0,1.00,...,0.0,-1.0,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-08-19,Premier League,Matchweek 2,Away,L,Stoke City,2017,Arsenal,0.0,0.80,...,3.0,-0.8,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-08-27,Premier League,Matchweek 3,Away,L,Liverpool,2017,Arsenal,0.0,-2.50,...,3.0,2.5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-09-09,Premier League,Matchweek 4,Home,W,Bournemouth,2017,Arsenal,3.0,1.60,...,0.0,-1.6,-3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-09-17,Premier League,Matchweek 5,Away,D,Chelsea,2017,Arsenal,1.0,0.60,...,1.0,-0.6,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13803,2021-04-17,Championship,Matchweek 42,Away,D,Swansea City,2020,Wycombe,0.3,-2.45,...,1.0,-1.0,-1.0,0.36,-1.39,-1.38,1.0,-1.0,-1.0,-1.385
13804,2021-04-21,Championship,Matchweek 43,Home,W,Bristol City,2020,Wycombe,0.9,0.65,...,1.0,-1.0,-1.0,0.12,-2.29,-2.98,1.0,-1.0,-1.0,-2.635
13805,2021-04-24,Championship,Matchweek 44,Away,L,Cardiff City,2020,Wycombe,0.0,-0.25,...,1.0,-1.0,-1.0,0.18,-1.07,-2.98,1.0,-1.0,-1.0,-2.025
13806,2021-05-01,Championship,Matchweek 45,Home,W,Bournemouth,2020,Wycombe,0.9,-2.95,...,1.0,-1.0,-1.0,0.72,-0.73,-0.18,1.0,-1.0,-1.0,-0.455
13807,2021-05-08,Championship,Matchweek 46,Away,W,Middlesbrough,2020,Wycombe,0.9,0.45,...,1.0,-1.0,-1.0,0.42,-1.55,-1.78,1.0,-1.0,-1.0,-1.665

In [7]:
home_team = []
away_team = []
for x in range(len(merged)):
    if merged["venue_x"][x] == 'Home':
        home_team.append(merged["new_team_x"][x])
        away_team.append(merged["new_team_y"][x])
    else:
        home_team.append(merged["new_team_y"][x])
        away_team.append(merged["new_team_x"][x])
    
merged["home_team"] = home_team
merged["away_team"] = away_team

In [8]:
merged.sort_values(["date","home_team"], inplace=True)
merged.reset_index(drop=True, inplace=True)
for x in range(len(merged)-1):
    if merged["date"][x] == merged["date"][x+1] and merged["new_team_x"][x] == merged["new_team_y"][x+1]: 
        merged.drop(index=x, inplace=True)
    else:
        continue
merged.reset_index(drop=True, inplace=True)

In [9]:
merged.drop(columns=['comp_y', 'round_y', 'venue_y','result_y','opponent_y', 'season_y','new_team_y'], inplace=True)

In [10]:
target = []
home_gf = []
away_gf = []
home_adjusted_gs = []
away_adjusted_gs = []
home_ga = []
away_ga = []
home_adjusted_gc = []
away_adjusted_gc = []
home_xg = []
away_xg = []
home_xga = []
away_xga = []
home_GD = []
away_GD = []
home_adjusted_GD = []
away_adjusted_GD = []
home_constant_GD = []
away_constant_GD = []
home_GD_form_5 = []
away_GD_form_5 = []
home_form_5 = []
away_form_5 = []
home_constant_GD_form_5 = []
away_constant_GD_form_5 = []
home_xGD = []
away_xGD = []
home_constant_xGD = []
away_constant_xGD = []
home_xGD_form_5 = []
away_xGD_form_5 = []
home_constant_xGD_form_5 = []
away_constant_xGD_form_5 = []
home_points = []
away_points = []
home_constant_points = []
away_constant_points = []
home_points_form_5 = []
away_points_form_5 = []
home_constant_points_form_5 = []
away_constant_points_form_5 = []
home_avg_pos = []
away_avg_pos = []
home_previous_position = []
away_previous_position = []
away_previous_expected_position = []
home_previous_expected_position = []
home_previous_points = []
away_previous_points = []
home_previous_GD = []
away_previous_GD = []
home_previous_xGD = []
away_previous_xGD = []
for x in range(len(merged)):
    if merged["venue_x"][x] == "Home":
        home_gf.append(merged["league_weighted_GF_x"][x])
        away_gf.append(merged["league_weighted_GF_y"][x])
        home_adjusted_gs.append(merged["Adjusted GS_x"][x])
        away_adjusted_gs.append(merged["Adjusted GS_y"][x])
        home_ga.append(merged["league_weighted_GA_x"][x])
        away_ga.append(merged["league_weighted_GA_y"][x])
        home_adjusted_gc.append(merged["Adjusted GC_x"][x])
        away_adjusted_gc.append(merged["Adjusted GC_y"][x])
        home_xg.append(merged["league_weighted_xG_x"][x])
        away_xg.append(merged["league_weighted_xG_y"][x])
        home_xga.append(merged["league_weighted_xGA_x"][x])
        away_xga.append(merged["league_weighted_xGA_y"][x])
        home_GD.append(merged["league_weighted_GD_x"][x])
        away_GD.append(merged["league_weighted_GD_y"][x])
        home_adjusted_GD.append(merged["Adjusted GD_x"][x])
        away_adjusted_GD.append(merged["Adjusted GD_y"][x])
        home_form_5.append(merged["Adjusted GD form last 5_x"][x])
        away_form_5.append(merged["Adjusted GD form last 5_y"][x])
        home_constant_GD.append(merged["constant_GD_x"][x])
        away_constant_GD.append(merged["constant_GD_y"][x])
        home_GD_form_5.append(merged['league_weighted_GD form last 5_x'][x])
        away_GD_form_5.append(merged['league_weighted_GD form last 5_y'][x])
        home_constant_GD_form_5.append(merged['constant_GD form last 5_x'][x])
        away_constant_GD_form_5.append(merged['constant_GD form last 5_y'][x])
        home_xGD.append(merged["league_weighted_xGD_x"][x])
        away_xGD.append(merged["league_weighted_xGD_y"][x])
        home_constant_xGD.append(merged["constant_xGD_x"][x])
        away_constant_xGD.append(merged["constant_xGD_y"][x])
        home_xGD_form_5.append(merged['league_weighted_xGD form last 5_x'][x])
        away_xGD_form_5.append(merged['league_weighted_xGD form last 5_y'][x])
        home_constant_xGD_form_5.append(merged['constant_xGD form last 5_x'][x])
        away_constant_xGD_form_5.append(merged['constant_xGD form last 5_y'][x])
        home_points.append(merged["league_weighted_points_x"][x])
        away_points.append(merged["league_weighted_points_y"][x])
        home_constant_points.append(merged["constant_points_x"][x])
        away_constant_points.append(merged["constant_points_y"][x])
        home_points_form_5.append(merged["league_weighted_points form last 5_x"][x])
        away_points_form_5.append(merged["league_weighted_points form last 5_y"][x])
        home_constant_points_form_5.append(merged["constant_points form last 5_x"][x])
        away_constant_points_form_5.append(merged["constant_points form last 5_y"][x])
        home_avg_pos.append(merged["new_team_avg_pos_x"][x])
        away_avg_pos.append(merged["new_team_avg_pos_y"][x])
        home_previous_position.append(merged["new_team_previous_position_x"][x])
        away_previous_position.append(merged["new_team_previous_position_y"][x])
        home_previous_expected_position.append(merged["new_team_previous_expected_position_x"][x])
        away_previous_expected_position.append(merged["new_team_previous_expected_position_y"][x])
        home_previous_points.append(merged["new_team_previous_points_x"][x])
        away_previous_points.append(merged["new_team_previous_points_y"][x])
        home_previous_GD.append(merged["new_team_previous_GD_x"][x])
        away_previous_GD.append(merged["new_team_previous_GD_y"][x])
        home_previous_xGD.append(merged["new_team_previous_xGD_x"][x])
        away_previous_xGD.append(merged["new_team_previous_xGD_y"][x])
        if merged["result_x"][x] == "W":
            target.append("HW")
        elif merged["result_x"][x] == "D":
            target.append("D")
        elif merged["result_x"][x] == "L":
            target.append("AW")
        else:
            target.append(float("nan"))
    else:
        
        if merged["result_x"][x] == "W":
            target.append("AW")
        elif merged["result_x"][x] == "D":
            target.append("D")
        elif merged["result_x"][x] == "L":
            target.append("HW")
        else:
            target.append(float("nan"))
        home_gf.append(merged["league_weighted_GF_y"][x])
        away_gf.append(merged["league_weighted_GF_x"][x])
        home_adjusted_gs.append(merged["Adjusted GS_y"][x])
        away_adjusted_gs.append(merged["Adjusted GS_x"][x])
        home_ga.append(merged["league_weighted_GA_y"][x])
        away_ga.append(merged["league_weighted_GA_x"][x])
        home_adjusted_gc.append(merged["Adjusted GC_y"][x])
        away_adjusted_gc.append(merged["Adjusted GC_x"][x])
        home_xg.append(merged["league_weighted_xG_y"][x])
        away_xg.append(merged["league_weighted_xG_x"][x])
        home_xga.append(merged["league_weighted_xGA_y"][x])
        away_xga.append(merged["league_weighted_xGA_x"][x])    
        home_GD.append(merged["league_weighted_GD_y"][x])
        away_GD.append(merged["league_weighted_GD_x"][x])
        home_adjusted_GD.append(merged["Adjusted GD_y"][x])
        away_adjusted_GD.append(merged["Adjusted GD_x"][x])
        home_form_5.append(merged["Adjusted GD form last 5_y"][x])
        away_form_5.append(merged["Adjusted GD form last 5_x"][x])
        home_constant_GD.append(merged["constant_GD_y"][x])
        away_constant_GD.append(merged["constant_GD_x"][x])
        home_GD_form_5.append(merged['league_weighted_GD form last 5_y'][x])
        away_GD_form_5.append(merged['league_weighted_GD form last 5_x'][x])
        home_constant_GD_form_5.append(merged['constant_GD form last 5_y'][x])
        away_constant_GD_form_5.append(merged['constant_GD form last 5_x'][x])
        home_xGD.append(merged["league_weighted_xGD_y"][x])
        away_xGD.append(merged["league_weighted_xGD_x"][x])
        home_constant_xGD.append(merged["constant_xGD_y"][x])
        away_constant_xGD.append(merged["constant_xGD_x"][x])
        home_xGD_form_5.append(merged['league_weighted_xGD form last 5_y'][x])
        away_xGD_form_5.append(merged['league_weighted_xGD form last 5_x'][x])
        home_constant_xGD_form_5.append(merged['constant_xGD form last 5_y'][x])
        away_constant_xGD_form_5.append(merged['constant_xGD form last 5_x'][x])
        home_points.append(merged["league_weighted_points_y"][x])
        away_points.append(merged["league_weighted_points_x"][x])
        home_constant_points.append(merged["constant_points_y"][x])
        away_constant_points.append(merged["constant_points_x"][x])
        home_points_form_5.append(merged["league_weighted_points form last 5_y"][x])
        away_points_form_5.append(merged["league_weighted_points form last 5_x"][x])
        home_constant_points_form_5.append(merged["constant_points form last 5_y"][x])
        away_constant_points_form_5.append(merged["constant_points form last 5_x"][x])
        home_avg_pos.append(merged["new_team_avg_pos_y"][x])
        away_avg_pos.append(merged["new_team_avg_pos_x"][x])
        home_previous_position.append(merged["new_team_previous_position_y"][x])
        away_previous_position.append(merged["new_team_previous_position_x"][x])
        home_previous_expected_position.append(merged["new_team_previous_expected_position_y"][x])
        away_previous_expected_position.append(merged["new_team_previous_expected_position_x"][x])
        home_previous_points.append(merged["new_team_previous_points_y"][x])
        away_previous_points.append(merged["new_team_previous_points_x"][x])
        home_previous_GD.append(merged["new_team_previous_GD_y"][x])
        away_previous_GD.append(merged["new_team_previous_GD_x"][x])
        home_previous_xGD.append(merged["new_team_previous_xGD_y"][x])
        away_previous_xGD.append(merged["new_team_previous_xGD_x"][x])

merged["target"] = target
merged["home GF"] = home_gf
merged["away GF"] = away_gf
merged["home adjusted GS"] = home_adjusted_gs
merged["away adjusted GS"] = away_adjusted_gs
merged["home GA"] = home_ga
merged["away GA"] = away_ga
merged["home adjusted GC"] = home_adjusted_gc
merged["away adjusted GC"] = away_adjusted_gc
merged["home xG"] = home_xg
merged["away xG"] = away_xg
merged["home xGA"] = home_xga
merged["away xGA"] = away_xga
merged["home GD"] = home_GD
merged["away GD"] = away_GD
merged["home adjusted GD"] = home_adjusted_GD
merged["away adjusted GD"] = away_adjusted_GD
merged["home form last 5"] = home_form_5
merged["away form last 5"] = away_form_5
merged["home constant GD"] = home_constant_GD
merged["away constant GD"] = away_constant_GD
merged["home GD form last 5"] = home_GD_form_5
merged["away GD form last 5"] = away_GD_form_5
merged["home constant GD form last 5"] = home_constant_GD_form_5
merged["away constant GD form last 5"] = away_constant_GD_form_5
merged["home xGD"] = home_xGD
merged["away xGD"] = away_xGD
merged["home constant xGD"] = home_constant_xGD
merged["away constant xGD"] = away_constant_xGD
merged["home xGD form last 5"] = home_xGD_form_5
merged["away xGD form last 5"] = away_xGD_form_5
merged["home constant xGD form last 5"] = home_constant_xGD_form_5
merged["away constant xGD form last 5"] = away_constant_xGD_form_5
merged["home points"] = home_points
merged["away points"] = away_points
merged["home constant points"] = home_constant_points
merged["away constant points"] = away_constant_points
merged["home points form last 5"] = home_points_form_5
merged["away points form last 5"] = away_points_form_5
merged["home constant points form last 5"] = home_constant_points_form_5
merged["away constant points form last 5"] = away_constant_points_form_5
merged["home avg pos"] = home_avg_pos
merged["away avg pos"] = away_avg_pos
merged["home previous position"] = home_previous_position
merged["away previous position"] = away_previous_position
merged["home previous expected position"] = home_previous_expected_position
merged["away previous expected position"] = away_previous_expected_position
merged["home previous points"] = home_previous_points
merged["away previous points"] = away_previous_points
merged["home previous GD"] = home_previous_GD
merged["away previous GD"] = away_previous_GD
merged["home previous xGD"] = home_previous_xGD
merged["away previous xGD"] = away_previous_xGD
merged

,date,comp_x,round_x,venue_x,result_x,opponent_x,season_x,new_team_x,league_weighted_points_x,league_weighted_xGD_x,...,home previous position,away previous position,home previous expected position,away previous expected position,home previous points,away previous points,home previous GD,away previous GD,home previous xGD,away previous xGD
0,2017-08-04,Championship,Matchweek 1,Home,W,Millwall,2017,Nott'ham Forest,0.9,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-08-04,Championship,Matchweek 1,Home,D,Derby County,2017,Sunderland,0.3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-08-05,Championship,Matchweek 1,Away,D,Aston Villa,2017,Hull City,0.3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-08-05,Championship,Matchweek 1,Home,W,Barnsley,2017,Bristol City,0.9,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-08-05,Championship,Matchweek 1,Away,W,Burton Albion,2017,Cardiff City,0.9,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6899,2025-05-06,Premier League,Matchweek 38,Home,NaN,Everton,2024,Newcastle Utd,NaN,NaN,...,7.0,12.0,5.0,10.0,60.0,48.0,23.00,-11.0,14.8,-1.8
6900,2025-05-06,Premier League,Matchweek 38,Home,NaN,Chelsea,2024,Nott'ham Forest,NaN,NaN,...,17.0,6.0,12.0,4.0,36.0,63.0,-18.00,14.0,-3.2,16.2
6901,2025-05-06,Premier League,Matchweek 38,Home,NaN,Arsenal,2024,Southampton,NaN,NaN,...,24.0,2.0,23.0,1.0,26.1,89.0,-57.88,62.0,-26.7,48.5
6902,2025-05-06,Premier League,Matchweek 38,Home,NaN,Brighton,2024,Tottenham,NaN,NaN,...,5.0,11.0,6.0,9.0,66.0,48.0,13.00,-7.0,4.5,0.9
6903,2025-05-06,Premier League,Matchweek 38,Home,NaN,Brentford,2024,Wolves,NaN,NaN,...,15.0,16.0,17.0,8.0,46.0,39.0,-15.00,-9.0,-20.7,2.2

In [11]:
merged.columns.to_list()

['date',
 'comp_x',
 'round_x',
 'venue_x',
 'result_x',
 'opponent_x',
 'season_x',
 'new_team_x',
 'league_weighted_points_x',
 'league_weighted_xGD_x',
 'league_weighted_GD_x',
 'league_weighted_GF_x',
 'league_weighted_GA_x',
 'league_weighted_xG_x',
 'league_weighted_xGA_x',
 'new_team_previous_points_x',
 'new_team_previous_xGD_x',
 'new_team_previous_GD_x',
 'new_team_previous_position_x',
 'new_team_previous_expected_position_x',
 'Adjusted GS_x',
 'Adjusted GC_x',
 'Adjusted GD_x',
 'new_team_avg_pos_x',
 'constant_points_x',
 'constant_xGD_x',
 'constant_GD_x',
 'league_weighted_points form last 5_x',
 'league_weighted_xGD form last 5_x',
 'league_weighted_GD form last 5_x',
 'constant_points form last 5_x',
 'constant_xGD form last 5_x',
 'constant_GD form last 5_x',
 'Adjusted GD form last 5_x',
 'league_weighted_points_y',
 'league_weighted_xGD_y',
 'league_weighted_GD_y',
 'league_weighted_GF_y',
 'league_weighted_GA_y',
 'league_weighted_xG_y',
 'league_weighted_xGA_y',
 'new_team_previous_points_y',
 'new_team_previous_xGD_y',
 'new_team_previous_GD_y',
 'new_team_previous_position_y',
 'new_team_previous_expected_position_y',
 'Adjusted GS_y',
 'Adjusted GC_y',
 'Adjusted GD_y',
 'new_team_avg_pos_y',
 'constant_points_y',
 'constant_xGD_y',
 'constant_GD_y',
 'league_weighted_points form last 5_y',
 'league_weighted_xGD form last 5_y',
 'league_weighted_GD form last 5_y',
 'constant_points form last 5_y',
 'constant_xGD form last 5_y',
 'constant_GD form last 5_y',
 'Adjusted GD form last 5_y',
 'home_team',
 'away_team',
 'target',
 'home GF',
 'away GF',
 'home adjusted GS',
 'away adjusted GS',
 'home GA',
 'away GA',
 'home adjusted GC',
 'away adjusted GC',
 'home xG',
 'away xG',
 'home xGA',
 'away xGA',
 'home GD',
 'away GD',
 'home adjusted GD',
 'away adjusted GD',
 'home form last 5',
 'away form last 5',
 'home constant GD',
 'away constant GD',
 'home GD form last 5',
 'away GD form last 5',
 'home constant GD form last 5',
 'away constant GD form last 5',
 'home xGD',
 'away xGD',
 'home constant xGD',
 'away constant xGD',
 'home xGD form last 5',
 'away xGD form last 5',
 'home constant xGD form last 5',
 'away constant xGD form last 5',
 'home points',
 'away points',
 'home constant points',
 'away constant points',
 'home points form last 5',
 'away points form last 5',
 'home constant points form last 5',
 'away constant points form last 5',
 'home avg pos',
 'away avg pos',
 'home previous position',
 'away previous position',
 'home previous expected position',
 'away previous expected position',
 'home previous points',
 'away previous points',
 'home previous GD',
 'away previous GD',
 'home previous xGD',
 'away previous xGD']

In [12]:
merged = merged[['date', 'comp_x','season_x','round_x','home_team', 'away_team', 'home points','away points','home constant points','away constant points', 'home GF', 'away GF','home adjusted GS','away adjusted GS','home GA', 'away GA', 'home adjusted GC',
                'away adjusted GC','home xG', 'away xG', 'home xGA', 'away xGA','home GD', 'away GD','home adjusted GD', 'away adjusted GD','home constant GD', 'away constant GD','home form last 5', 'away form last 5', 'home GD form last 5','away GD form last 5','home constant GD form last 5','away constant GD form last 5', 'home xGD', 'away xGD','home constant xGD', 'away constant xGD', 'home xGD form last 5', 'away xGD form last 5','home constant xGD form last 5', 'away constant xGD form last 5',
                 'home points form last 5', 'away points form last 5','home constant points form last 5','away constant points form last 5','home avg pos', 'away avg pos', 'home previous position', 'away previous position', 'home previous expected position', 'away previous expected position','home previous points', 'away previous points', 'home previous GD',
                 'away previous GD', 'home previous xGD', 'away previous xGD']]

In [13]:
merged

,date,comp_x,season_x,round_x,home_team,away_team,home points,away points,home constant points,away constant points,...,home previous position,away previous position,home previous expected position,away previous expected position,home previous points,away previous points,home previous GD,away previous GD,home previous xGD,away previous xGD
0,2017-08-04,Championship,2017,Matchweek 1,Nott'ham Forest,Millwall,0.9,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-08-04,Championship,2017,Matchweek 1,Sunderland,Derby County,0.3,0.3,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-08-05,Championship,2017,Matchweek 1,Aston Villa,Hull City,0.3,0.3,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-08-05,Championship,2017,Matchweek 1,Bristol City,Barnsley,0.9,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-08-05,Championship,2017,Matchweek 1,Burton Albion,Cardiff City,0.0,0.9,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6899,2025-05-06,Premier League,2024,Matchweek 38,Newcastle Utd,Everton,NaN,NaN,NaN,NaN,...,7.0,12.0,5.0,10.0,60.0,48.0,23.00,-11.0,14.8,-1.8
6900,2025-05-06,Premier League,2024,Matchweek 38,Nott'ham Forest,Chelsea,NaN,NaN,NaN,NaN,...,17.0,6.0,12.0,4.0,36.0,63.0,-18.00,14.0,-3.2,16.2
6901,2025-05-06,Premier League,2024,Matchweek 38,Southampton,Arsenal,NaN,NaN,NaN,NaN,...,24.0,2.0,23.0,1.0,26.1,89.0,-57.88,62.0,-26.7,48.5
6902,2025-05-06,Premier League,2024,Matchweek 38,Tottenham,Brighton,NaN,NaN,NaN,NaN,...,5.0,11.0,6.0,9.0,66.0,48.0,13.00,-7.0,4.5,0.9
6903,2025-05-06,Premier League,2024,Matchweek 38,Wolves,Brentford,NaN,NaN,NaN,NaN,...,15.0,16.0,17.0,8.0,46.0,39.0,-15.00,-9.0,-20.7,2.2

In [14]:
merged.to_excel(r"C:\Users\George\Documents\University\Masters\DISS\Datasets\Match Dataset Merged and Duplicates Removed (3).xlsx")